# Generated by Django 4.1.5 on 2023-01-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_publisher_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="asst_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_asst_manager_proj",
                to="myapp.person",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_manager_proj",
                to="myapp.person",
            ),
        ),
    ]
