# Generated by Django 4.1.5 on 2023-01-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_project_asst_manager_alter_project_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="myapp.publisher",
            ),
        ),
    ]
