# Generated by Django 4.1.5 on 2023-01-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_project_asst_manager_alter_project_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="person_image/")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.person"
                    ),
                ),
            ],
        ),
    ]
