# Generated by Django 4.1.5 on 2023-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_personimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="personimage",
            name="image_info",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
