# Generated by Django 4.1.5 on 2023-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_personimage_image_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personimage",
            name="image_info",
            field=models.CharField(
                blank=True, default="image", max_length=200, null=True
            ),
        ),
    ]
